import Link from "next/link";
import Footer from "../components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Link href="/about-us">About Page</Link> | <Link href="/">Home</Link>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
