import "../assets/main.css";

import Link from "next/link";
import Footer from "../components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <div>
            <Link href="/about-us">About Page</Link> |{" "}
            <Link href="/">Home</Link>
          </div>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
